### ISSUE TITLE
there are errors when i read data with data_reader.py 

### ISSUE THREAD

**Issue by Haena0320** [klimzaporojets/e2e-kb-ie#2]
**Hello
When I try to run train.py as below, there are some errors...**

python src/train.py --config_file experiments/attention_dwie_kb_both.json --path results

**Is there any upgrade version of datareader.py ?
I didn't work with the dat**a 

Traceback (most recent call last):
  File "src/train.py", line 306, in <module>
    datasets, data, evaluate = create_datasets(config, dictionaries)
  File "/user15/workspace/joint_extraction/src/data/data_reader.py", line 64, in create_datasets
    datasets = {name: DatasetCPN(name, value, config, dictionaries) for name, value in config['datasets'].items()}
  File "/user15/workspace/joint_extraction/src/data/data_reader.py", line 64, in <dictcomp>
    datasets = {name: DatasetCPN(name, value, config, dictionaries) for name, value in config['datasets'].items()}
  File "/user15/workspace/joint_extraction/src/data/data_reader.py", line 124, in __init__
    self.load(os.path.join(path, filename))
  File "/user15/workspace/joint_extraction/src/data/data_reader.py", line 163, in load
    tokens = self.tokenizer.tokenize(data['content'])
KeyError: 'content'

**Comment by klimzaporojets** [comment]
Hi, 
Thanks for your interest in our work, 

Please make sure to run ./download_data.sh script (specially the "src/dwie_download.py --tokenize True" line which downloads the 'content' field in the dataset files). I just updated the repo, so you may need to download the latest version. 

Please let us know if this solves the problem. 

Best, 

Klim
